// This is a skeleton starter React page generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import * as ph from "@plasmicapp/host";

import { ScreenVariantProvider } from "../components/plasmic/mdaeschlimann_com/PlasmicGlobalVariant__Screen";
import { PlasmicAccueil } from "../components/plasmic/mdaeschlimann_com/PlasmicAccueil";
import { useRouter } from "next/router";

function Contact() {
  return (
    <ph.PageParamsProvider
      params={useRouter()?.query}
      query={useRouter()?.query}
    >
      <PlasmicAccueil contact={true}         
      root={{
          props: {
            onSubmit: (event: any) => {
              let checked = false;
              const formData = new FormData(event.target);
              const data = formData.entries()
              for (const entry of data) {
                if (entry[0] === "checked") {
                  checked = true
                }
              }
              if (!checked) {
                event.preventDefault();
                alert("Veuillez confirmer que vous souhaitez recevoir la newsletter en cochant la case prévue à cet effet.")
              }
            }
          }
        }}
 />
    </ph.PageParamsProvider>
  );
}

export default Contact;
