// This is a skeleton starter React page generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import * as ph from "@plasmicapp/host";

import { ScreenVariantProvider } from "../components/plasmic/mdaeschlimann_com/PlasmicGlobalVariant__Screen";
import { PlasmicAccueil } from "../components/plasmic/mdaeschlimann_com/PlasmicAccueil";
import { useRouter } from "next/router";

function Accueil() {
  // Use PlasmicAccueil to render this component as it was
  // designed in Plasmic, by activating the appropriate variants,
  // attaching the appropriate event handlers, etc.  You
  // can also install whatever React hooks you need here to manage state or
  // fetch data.
  //
  // Props you can pass into PlasmicAccueil are:
  // 1. Variants you want to activate,
  // 2. Contents for slots you want to fill,
  // 3. Overrides for any named node in the component to attach behavior and data,
  // 4. Props to set on the root node.
  //
  // By default, PlasmicAccueil is wrapped by your project's global
  // variant context providers. These wrappers may be moved to
  // Next.js Custom App component
  // (https://nextjs.org/docs/advanced-features/custom-app).
  return (
    <ph.PageParamsProvider
      params={useRouter()?.query}
      query={useRouter()?.query}
    >
      <PlasmicAccueil
        root={{
          props: {
            onSubmit: (event: any) => {
              let checked = false;
              const formData = new FormData(event.target);
              const data = formData.entries()
              for (const entry of data) {
                if (entry[0] === "checked") {
                  checked = true
                }
              }
              if (!checked) {
                event.preventDefault();
                alert("Veuillez confirmer que vous souhaitez recevoir la newsletter en cochant la case prévue à cet effet.")
              }
              if (event.target.querySelector('.PhoneInputInput').getAttribute("error")) {
                event.preventDefault();
                alert("Merci de vérifier le numéro de téléphone fourni.")
              }
            }
          }
        }}
      />
    </ph.PageParamsProvider>
  );
}

export default Accueil;
